sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - python setup.py install
  - pip install flake8 requests_mock
  - pip install --upgrade pytest
  - pip install pytest-cov
script:
  - flake8 $(git ls-files mechanicalsoup/'*.py') example.py
  - py.test
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
